format = """[$battery$character](bold maude)"""
right_format = """[$all](bold mauve)$cmd_duration$rust$c$lua$directory$git_status$git_branch$git_commit"""
add_newline = false
palette = "catppuccin_mocha"

[character]
success_symbol = '[λ](bold mauve)'
error_symbol = '[λ](bold mauve)'
vimcmd_symbol = '[λ](italic mauve)'
vimcmd_visual_symbol = '[λ](italic mauve)'
vimcmd_replace_one_symbol = '[O](bold red)'
vimcmd_replace_symbol = '[O](bold green)'

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'bold blue'
read_only = ''
read_only_style = 'maroon'
truncation_symbol = '…/'

[[battery.display]]
threshold = 5
style = 'bold red'
discharging_symbol = '󰂎 '

[git_branch]
format = '[$branch(:$remote_branch)]($style)'
style = 'italic flamingo'

[git_commit]
commit_hash_length = 6
format = ' [$hash$tag]($style)'
style = 'italic rosewater'

[git_status]
style = 'italic maron'
typechanged = '  '
format = '   [$all_status$ahead_behind]($style) '

[cmd_duration]
min_time = 1_500
format = '[$duration]($style) '
style = 'text'

[package]
disabled = true

[c]
format = '[$symbol](blue)'
symbol = '[  ](blue)'
detect_files = [
    'Makefile',
    'CMakeLists.txt',
    'main.c',
    'main.cpp',
    'Main.c',
    'Main.cpp',
]

[lua]
format = '[$symbol](sky)'
symbol = '[  ](sky)'


[rust]
format = '[$symbol](peach)'
symbol = '[  ](peach)'


# [package]
# disabled=false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
